# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Squid-Guard
version:      0.09
version_from: lib/Squid/Guard.pm
installdirs:  site
requires:
    DB_File:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
